// objeto de datos
export const VIDatosMaterias = [
    {
        id: 1,
        nombre: "AM1",
        estado: 1,
        materiasQueActualiza: [9, 10, 17, 19, 22, 18],
        materiasQueNecesitaRegulares: [],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 2,
        nombre: "AGA",
        estado: 1,
        materiasQueActualiza: [9, 17, 19, 22, 18],
        materiasQueNecesitaRegulares: [],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 3,
        nombre: "FIS1",
        estado: 1,
        materiasQueActualiza: [10, 21],
        materiasQueNecesitaRegulares: [],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 4,
        nombre: "INGLES",
        estado: 1,
        materiasQueActualiza: [12, 23],
        materiasQueNecesitaRegulares: [],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 5,
        nombre: "LED/MAD",
        estado: 1,
        materiasQueActualiza: [13, 14, 20],
        materiasQueNecesitaRegulares: [],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 6,
        nombre: "AED",
        estado: 1,
        materiasQueActualiza: [13, 14, 16, 20, 23, 49, 50, 55],
        materiasQueNecesitaRegulares: [],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 7,
        nombre: "ACO",
        estado: 1,
        materiasQueActualiza: [15, 21],
        materiasQueNecesitaRegulares: [],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 8,
        nombre: "SPN/SOR",
        estado: 1,
        materiasQueActualiza: [49, 52, 53, 56, 16, 23],
        materiasQueNecesitaRegulares: [],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 11,
        nombre: "ISO",
        estado: 1,
        materiasQueActualiza: [24],
        materiasQueNecesitaRegulares: [],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 9,
        nombre: "AM2",
        estado: 0,
        materiasQueActualiza: [22, 28, 29, 32],
        materiasQueNecesitaRegulares: [1, 2],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 10,
        nombre: "FIS2",
        estado: 0,
        materiasQueActualiza: [29],
        materiasQueNecesitaRegulares: [1, 3],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 12,
        nombre: "INGLES 2",
        estado: 0,
        materiasQueActualiza: [36],
        materiasQueNecesitaRegulares: [4],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 13,
        nombre: "SSL",
        estado: 0,
        materiasQueActualiza: [19, 25, 49, 50, 51, 55, 57, 68],
        materiasQueNecesitaRegulares: [5, 6],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 14,
        nombre: "PPR",
        estado: 0,
        materiasQueActualiza: [20, 23, 25, 49, 50, 51, 57, 58, 68],
        materiasQueNecesitaRegulares: [5, 6],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 15,
        nombre: "SOP",
        estado: 0,
        materiasQueActualiza: [26],
        materiasQueNecesitaRegulares: [7],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 16,
        nombre: "ASI",
        estado: 0,
        materiasQueActualiza: [49, 52, 53, 56, 63, 66, 19, 20, 23, 30],
        materiasQueNecesitaRegulares: [6, 8],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 17,
        nombre: "PYE",
        estado: 0,
        materiasQueActualiza: [27, 28, 31, 32],
        materiasQueNecesitaRegulares: [1, 2],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 18,
        nombre: "ECO",
        estado: 1,
        materiasQueActualiza: [30, 33, 34],
        materiasQueNecesitaRegulares: [],
        materiasQueNecesitaAprobadas: [1, 2],
    },
    {
        id: 19,
        nombre: "BDA/GDA",
        estado: 0,
        materiasQueActualiza: [25, 32, 51, 52, 53, 54, 56, 57, 58, 63, 64, 65, 66, 67, 68],
        materiasQueNecesitaRegulares: [13, 16],
        materiasQueNecesitaAprobadas: [1, 2],
    },
    {
        id: 20,
        nombre: "DDS",
        estado: 0,
        materiasQueActualiza: [25, 35, 36, 51, 54, 57, 58, 59, 60, 61, 62, 65, 66, 67, 68],
        materiasQueNecesitaRegulares: [14, 16],
        materiasQueNecesitaAprobadas: [5, 6],
    },
    {
        id: 21,
        nombre: "COM",
        estado: 0,
        materiasQueActualiza: [26, 35],
        materiasQueNecesitaRegulares: [],
        materiasQueNecesitaAprobadas: [3, 7],
    },
    {
        id: 22,
        nombre: "ANumerico",
        estado: 0,
        materiasQueActualiza: [27, 29, 31],
        materiasQueNecesitaRegulares: [9],
        materiasQueNecesitaAprobadas: [1, 2],
    },
    {
        id: 23,
        nombre: "DSI",
        estado: 0,
        materiasQueActualiza: [25, 30, 33, 36],
        materiasQueNecesitaRegulares: [14, 16],
        materiasQueNecesitaAprobadas: [4, 6, 8],
    },
    {
        id: 24,
        nombre: "LEG",
        estado: 0,
        materiasQueActualiza: [34],
        materiasQueNecesitaRegulares: [11],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 25,
        nombre: "Ing y Calidad Software",
        estado: 0,
        materiasQueActualiza: [65, 36],
        materiasQueNecesitaRegulares: [19, 20, 23],
        materiasQueNecesitaAprobadas: [13, 14],
    },
    {
        id: 26,
        nombre: "Redes de datos",
        estado: 0,
        materiasQueActualiza: [35, 36, 58, 66, 67, 68],
        materiasQueNecesitaRegulares: [15, 21],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 27,
        nombre: "IOP",
        estado: 0,
        materiasQueActualiza: [64, 33],
        materiasQueNecesitaRegulares: [17, 22],
        materiasQueNecesitaAprobadas: [],
    },
    {
        id: 28,
        nombre: "SIM",
        estado: 0,
        materiasQueActualiza: [31, 32],
        materiasQueNecesitaRegulares: [17],
        materiasQueNecesitaAprobadas: [9],
    },
    {
        id: 29,
        nombre: "Tec Automat",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [10, 22],
        materiasQueNecesitaAprobadas: [9],
    },
    {
        id: 30,
        nombre: "Adm sistemas inf",
        estado: 0,
        materiasQueActualiza: [59, 60, 61, 62, 63, 34, 35, 36],
        materiasQueNecesitaRegulares: [18, 23],
        materiasQueNecesitaAprobadas: [16],
    },
    {
        id: 31,
        nombre: "IA",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [28],
        materiasQueNecesitaAprobadas: [17, 22],
    },
    {
        id: 32,
        nombre: "Ciencia de datos",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [28],
        materiasQueNecesitaAprobadas: [17, 19],
    },
    {
        id: 33,
        nombre: "Sist Gestion",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [18, 27],
        materiasQueNecesitaAprobadas: [23],
    },
    {
        id: 34,
        nombre: "Gestión Gerencial",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [24, 30],
        materiasQueNecesitaAprobadas: [18],
    },
    {
        id: 35,
        nombre: "Seguridad",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [26, 30],
        materiasQueNecesitaAprobadas: [20, 21],
    },
    {
        id: 36,
        nombre: "Proyecto Final",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [25, 26, 30],
        materiasQueNecesitaAprobadas: [12, 20, 23],
    }, // seminario id 49 + 19 electivas id 50-68 tercer año
    {
        id: 49,
        nombre: "Seminario",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [16],
        materiasQueNecesitaAprobadas: [6, 8, 13, 14],
    },
    {
        id: 50,
        nombre: "BACK",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [13, 14],
        materiasQueNecesitaAprobadas: [6],
    },// cuarto año
    {
        id: 51,
        nombre: "Green Software",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [20, 19],
        materiasQueNecesitaAprobadas: [13, 14],
    },
    {
        id: 52,
        nombre: "Gestion Ind. de la Prod.",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [19],
        materiasQueNecesitaAprobadas: [8, 16],
    },
    {
        id: 53,
        nombre: "Gestion Mejora Proc.",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [19],
        materiasQueNecesitaAprobadas: [8, 16],
    },
    {
        id: 54,
        nombre: "DevOps",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [20, 19],
        materiasQueNecesitaAprobadas: [13, 14],
    },
    {
        id: 55,
        nombre: "DAO",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [13],
        materiasQueNecesitaAprobadas: [6],
    },
    {
        id: 56,
        nombre: "Com. Multimedial",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [19],
        materiasQueNecesitaAprobadas: [8, 16],
    },
    {
        id: 57,
        nombre: "Arq. Soft",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [20, 19],
        materiasQueNecesitaAprobadas: [13, 14],
    },//quinto año
    {
        id: 58,
        nombre: "Blockchain",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [26, 19],
        materiasQueNecesitaAprobadas: [14, 20],
    },
    {
        id: 59,
        nombre: "Creatividad e Innovación",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [30],
        materiasQueNecesitaAprobadas: [20],
    },
    {
        id: 60,
        nombre: "Auditoría",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [30],
        materiasQueNecesitaAprobadas: [20],
    },
    {
        id: 61,
        nombre: "Gerenciamiento Estrat.",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [30],
        materiasQueNecesitaAprobadas: [20],
    },
    {
        id: 62,
        nombre: "Consultoría",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [30],
        materiasQueNecesitaAprobadas: [20],
    },
    {
        id: 63,
        nombre: "Emprendimientos Tec",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [30],
        materiasQueNecesitaAprobadas: [16, 19],
    },
    {
        id: 64,
        nombre: "Decisiones en Esc. Comp.",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [27],
        materiasQueNecesitaAprobadas: [19],
    },
    {
        id: 65,
        nombre: "Testing",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [25],
        materiasQueNecesitaAprobadas: [19, 20],
    },
    {
        id: 66,
        nombre: "Seguridad Desarrollo SW",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [26, 19],
        materiasQueNecesitaAprobadas: [20, 16],
    },
    {
        id: 67,
        nombre: "Integracion Apps Ent. Web",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [26, 19],
        materiasQueNecesitaAprobadas: [20, 19],
    },
    {
        id: 68,
        nombre: "Ing. SW de fuentes abiertas",
        estado: 0,
        materiasQueActualiza: [],
        materiasQueNecesitaRegulares: [26, 19, 20],
        materiasQueNecesitaAprobadas: [13, 14],
    },
];